dist: jammy
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/brownplt/pyret-docs.git
  - RACKET_DIR: "~/racket"
  - RACKET_VERSION: '7.6'
  - secure: LLFEGDikZDFTdkok/f+n31eoTx270xCQ89kuCdnAYZdPrfeecaLYJ2qZZwBKpXHilkIsVe0z0C/iUixptTAzYbRoyLf8heSP9FC+yOl10ZrKcEwDGxoGST2QeDbYMnPqvtJcRqFq7noYE0RqV/4nf9DqdggTK3Kd0Moi9/h+lbc=
  - secure: QUV2+be9MgwujoT3+2nVJaXEvoVL3osUBZlJHlXEMWGADUY3xzVCN4sH3a3K5W8iSP9CAL0ZTSYi/QJe1ixx/gKDQMG75NP52A+WiWOI04gwY+QScBkir4btKiHTZM+BgLYGpVuItqaQT9I86AHKiib1oi+2AsEOFnFs0mujbG4=
before_install:
- nvm install 16.13.0
- nvm use 16.13.0
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash
- export PATH="${RACKET_DIR}/bin:${PATH}"
- raco pkg install --auto --no-docs frog
- gem install nokogiri
- gem install logger
script:
- npm install
- make pages
deploy:
  provider: s3
  edge: true
  bucket: pyret-docs
  local_dir: site
  skip_cleanup: true
  access_key_id:
    secure: eeRrmzlX8S7ALsCZorKm1+YoTZGFPkhCzYoeaX8Qgm6AqHB41+gems+Z6DcB8sp7/sjgwBXS9NWmvQ3PRp558/XOAThw5R4rcJ8SWlsYAqp2T8htmnNhjkjnvZlnM0T6YJr/1wXS9evtykJ2FBEkYttFcaT2AkoUvXQBZLAcgp4=
  secret_access_key:
    secure: W963gvHvi+S1WrfOBWKP7dAHkNL6XZkpYfkW5QsH9J+4aLZOJQkPjUkOWwdqgDJm08LIX4P9hMeGzLVJOHzsUkpse8WhHS/+bbaunSb8mfDOec4Xhis700UJs0CaS3jXOAbWXQp+EQPcNEtWhGPAB9XanEb5swboOMrUsjS8dDc=
